### ISSUE TITLE
请教大佬，通过chatGPT生成的图片，一般怎么下载呀，我通过URL下载的时候会报错

### ISSUE THREAD

**Issue by beifeng15** [LiLittleCat/ChatGPT#4]
chatGPT生成的url为：
https://oaidalleapiprodscus.blob.core.windows.net/private/org-x2tDof6L8GQcT9HVev8uEEvq/user-QKO2z3TMxUYqYwTpR55INmEC/img-qBCyuxcVP2RHrpvmUUU3AjkP.png?st=2023-03-10T14%3A45%3A30Z&se=2023-03-10T16%3A45%3A30Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-03-10T03%3A35%3A18Z&ske=2023-03-11T03%3A35%3A18Z&sks=b&skv=2021-08-06&sig=lCj9fQwr6USg1ryf4wNB3HSRiAdpDE1XEmV9y9eKluQ%3D

Linux上的代码为：
` URL url = new URL(imageUrl);
File outputFile = File.createTempFile("ceshi", suffix,new File("/home/work/log/openAi"));

FileUtils.copyURLToFile(url, outputFile);`
报错信息如下：
2023-03-11 00:14:37,137|ERROR|http-nio-9750-exec-6|c.x.b.a.m.utils.GlobalExceptionHandler|21|接口出错=/api/openAi/testDownLoadByUrl,e = java.net.UnknownHostException: oaidalleapipro dscus.blob.core.windows.net
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.protocol.https.HttpsClient.(HttpsClient.java:264)
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)

**Comment by beifeng15** [comment]
@LiLittleCat 感谢大佬的热心解答，但应该不是url的问题。我使用Windows直接打开的时候，都能正常返回的
1. 因为那个连接好像有一定的过期时间，过期之后，就不能直接打开了。
2. 我尝试了很多中通过url下载文件的方法，但是只要是openai产出的图片，均会超时。
![image](https://user-images.githubusercontent.com/43507256/224490817-7f4a2295-68d9-4843-a642-c546fea6d080.png)

所以咨询一下大佬，有没有更优雅的方式将产出的图片进行保存存储的呢。

**Comment by LiLittleCat** [comment]
@beifeng15 你的连接我用 WIndows 怎么打不开啊，:thinking:，如果是 HTTP 路径好像只有这种方式了吧。另外，你这个 host `oaidalleapiprodscus.blob.core.windows.net`在你的 Linux 机器上能访问吗？有没有加到 hosts 里。

**Comment by beifeng15** [comment]
@LiLittleCat 这个应该能打开：我刚生产的：https://oaidalleapiprodscus.blob.core.windows.net/private/org-Rd7OEttY63MZbkck6NB72uDm/user-SFX7L7eqWP8TwtITEEgL3Xvc/img-kSfbaRfhUTJ6YI9V8iWYodmk.png?st=2023-03-11T14%3A28%3A55Z&se=2023-03-11T16%3A28%3A55Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-03-10T17%3A47%3A56Z&ske=2023-03-11T17%3A47%3A56Z&sks=b&skv=2021-08-06&sig=WLniQ7PvCQt69M8RKxdDaHjYAOX8%2BwJMYGhUut5AVwg%3D

机器看样子ping不通，一直卡在这里：
![image](https://user-images.githubusercontent.com/43507256/224493198-abff2949-a793-4262-bda0-1fcae6aadb31.png)

**Comment by LiLittleCat** [comment]
@beifeng15 可以，这个我也能打开，那就是 hosts 的问题

**Comment by beifeng15** [comment]
@LiLittleCat 这种有办法解决吗，其实我用了海外的机器去ping，也一样ping不通
